(module (argyle base type fn))
(use (argyle base fn))

(defp fun procedure)
(defp fn-doc procedure-documentation)
(defp fn-min-arity procedure-minimum-arity)
(defp fn-name procedure-name)
(defp fn-prop procedure-property)
(defp fn-props procedure-properties)
(defp fn-src procedure-source)
(defp fn-w/setr? procedure-with-setter?)
(defp fn? procedure?)
