(ns (argyle base type lst))
(use (argyle base fn)
     (srfi srfi-1))
(export filter reduce)

(defp lst list)
(defp lst? list?)
(defp empty? null?)
(defp lst-> list->array)
(defp lst-> list->bitvector)
(defp lst-> list->char-set)
(defp lst-> list->string)
(defp lst-> list->symbol)
(defp lst-> list->vector)
(defp lst-cpy list-copy)
(defp cdr: list-cdr-ref)
(defp cdr! list-cdr-set!)
(defp lst-idx list-index)
(defp lst: list-ref)
(defp lst! list-set!)
(defp lst-hd list-head)
(defp lst-tl list-tail)
(defp unique delete-duplicates)
(defp unique! delete-duplicates!)
(defp range iota)
