(module (arguile)
  :duplicates (last))
(use (arguile base)
     (arguile match)
     (arguile data)
     (arguile data tbl)
     (arguile data vec)
     (arguile data q)
     (arguile generic)
     (arguile loop)
     (arguile nested-loop)
     (arguile conc)
     (arguile reader)
     
     (ice-9 match)
     (ice-9 receive)
     (srfi srfi-45))

(re-export-modules
 (arguile base)
 (arguile match)
 (arguile data)
 (arguile data tbl)
 (arguile data vec)
 (arguile data q)
 (arguile generic)
 (arguile loop)
 (arguile nested-loop)
 (arguile conc)
 
 (ice-9 match)
 (ice-9 receive)
 (srfi srfi-45))
