(module (argyle base))
(use (argyle base mac)
     (argyle base fn)
     (argyle base ctrl)
     (argyle base type)
     (argyle base generic)
     (argyle base err)
     (argyle base io)
     (argyle base math)
     (argyle base module))

(re-export-modules (argyle base mac)
                   (argyle base fn)
                   (argyle base ctrl)
                   (argyle base type)
                   (argyle base generic)
                   (argyle base err)
                   (argyle base io)
                   (argyle base math)
                   (argyle base module))
