(ns (argyle base))
(use (argyle base mac)
     (argyle base fn)
     (argyle base ctrl)
     (argyle base type)
     (argyle base generic)
     (argyle base err)
     (argyle base io)
     (argyle base math)
     (argyle base ns))

(re-export-ns (argyle base mac)
                   (argyle base fn)
                   (argyle base ctrl)
                   (argyle base type)
                   (argyle base generic)
                   (argyle base err)
                   (argyle base io)
                   (argyle base math)
                   (argyle base ns))
