(module (arguile base type lst))
(use (arguile base fn))

(defp lst list)
(defp lst? list?)
(defp lst-> list->array)
(defp lst-> list->bitvector)
(defp lst-> list->char-set)
(defp lst-> list->string)
(defp lst-> list->symbol)
(defp lst-> list->vector)
(defp lst-cpy list-copy)
(defp cdr: list-cdr-ref)
(defp cdr! list-cdr-set!)
(defp lst-idx list-index)
(defp lst: list-ref)
(defp lst! list-set!)
(defp lst-hd list-head)
(defp lst-tl list-tail)

