(module (arguile base))

(use (arguile base module)
     (arguile base mac)
     (arguile base fn)
     (arguile base ctrl)
     (arguile base type)
     (arguile base generic)
     (arguile base err)
     (arguile base io))

(re-export-modules (arguile base module)
                   (arguile base mac)
                   (arguile base fn)
                   (arguile base ctrl)
                   (arguile base type)
                   (arguile base generic)
                   (arguile base err)
                   (arguile base io))
